/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:43eebeee-9309-4c01-851a-697dee496b14",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_w07sxFzAH",
    "aws_user_pools_web_client_id": "2fs9e891fmol9d6t4sdhlb3ne1",
    "oauth": {}
};


export default awsmobile;
