/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ca2f8819-9d1a-4f04-9f39-eca811dfaac3",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QAAcnW0bK",
    "aws_user_pools_web_client_id": "5pabcv4fcoumsdd80i5qg82d4e",
    "oauth": {},
<<<<<<< HEAD
    "aws_appsync_graphqlEndpoint": "http://192.168.1.88:20002/graphql",
=======
    "aws_appsync_graphqlEndpoint": "http://192.168.137.1:20002/graphql",
>>>>>>> 873cac5896f9694dd92e76469e367841a8dfb5f4
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_user_files_s3_bucket": "studyscout7cd0119a23d74e2ca4dbd50b3fd47127161706-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
